### PR TITLE
Added _bscore_woocommerce.scss collector

### PR DESCRIPTION
**Pull request by crftwrk**
Adding `_bscore_woocommerce.scss` for Pull request [#41](https://github.com/bootscore/bootscore/pull/41)

### CODE REVIEW

**Comment by Axos11** [comment]
I'm not quite sure if the actual file _bscore_woocommerce.scss is existing in that commit. If not, I would add it with a short comment just to explain why its there and empty.

**Comment by crftwrk** [comment]
File is in parent theme and there is a comment why it's still empty https://github.com/bootscore/bootscore/pull/41/files

**Comment by crftwrk** [comment]
Added a short description to import files.

PR in parent theme must be merged first https://github.com/bootscore/bootscore/pull/41/files

**Comment by crftwrk** [comment]
@Axos11 since the talk this morning, I should more explain why things are as they are and what's the goal of it at the end.

In earlier Version, theme had 4 enqueued CSS files:

- precompiled bootstrap.min.css
- style.css
- fontawesome.min.css
- woocommerce-style.css (bootcommerce-child)

The bootstrap.min.css is enqueued in existing child-theme installations and we cannot change this name roughly without crashing users themes. 

Adding Bootstrap source and compiler was a game changer. We decided to do move step-by-step all files to SCSS and merge them into one enqueued CSS file add the end. For each step, user must update his child. An update guide is written in the blog and user gets informed by newsletter.

- 5.1.1.1 Added source and compiler. Users had to `@import` files in their child. Added an empty `_bscore_style.scss` to prepare moving theme styles to there. Added `_fontawesome.scss`, (that could have been wrong if we change the font https://github.com/bootscore/bootscore/issues/46). And missed to add `_bscore_woocommerce.scss` (wrong as well)
- 5.2.0.0 moves the content from style.css to scss files, what we did here https://github.com/bootscore/bootscore/pull/33 and will be compiled to bootstrap.min.css as well. This pull request adds the `@import` for the (still empty) `_bscore_woocommerce.scss` in parent-theme to prepare moving the woocommerce-style.css to scss.
- 5.2.1.1 Because users has import this file now, we can moving woocommerce-style.css to scss files and delete it. One file request less.
- 5.2.1.2 Depends on what we do with icons. For example existing `fontawesome.min.css` will be copied to `_fontawesome.scss` and file deleted. One file request less.
- 5.3.0.0 We have still 2 enqueued css files. style.css and bootstrap.min.css. We should set the compiler output to style.css and delete bootstrap.min.css. Now, only 1 css file is loaded.

What I mean with that is, that something like name bootstrap.min.css is confusing, because this file contains more than Bootstrap. But we have to change this step-by-step. First catch all css to scss and delete css files, then pushing to style.css.

**Review by Axos11 — APPROVED** [review]

**Review by crftwrk — COMMENTED** [review]
Ok

**Pull request merged**
